# Generated by Django 4.2.5 on 2023-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserFirstName', models.CharField(max_length=50)),
                ('UserLastName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(choices=[('NE', 'Nebraska'), ('IA', 'Iowa')], max_length=2)),
                ('ZipCode', models.CharField(max_length=10)),
            ],
        ),
    ]
