# Generated by Django 4.2.5 on 2023-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('MenuID', models.AutoField(primary_key=True, serialize=False)),
                ('foodCategory', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Soups and Salads', 'Soups and Salads'), ('Sandwiches & Burgers', 'Sandwiches & Burgers'), ('Main Entrees', 'Main Entrees'), ('Desserts', 'Desserts'), ('Sides', 'Sides'), ('Drinks', 'Drinks')], max_length=20)),
                ('foodName', models.CharField(max_length=100)),
                ('foodPic', models.ImageField(upload_to='food_pics/')),
                ('foodSize', models.CharField(choices=[('Tiny Ones', 'Tiny Ones'), ('Small Kid', 'Small Kid'), ('Big Kid', 'Big Kid'), ('Teen', 'Teen'), ('Adult', 'Adult')], max_length=20)),
                ('foodPrice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
