# Generated by Django 4.2.5 on 2023-10-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_foodmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('userSelect', models.BooleanField()),
                ('nameOnCard', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=19)),
                ('expDate', models.CharField(max_length=6)),
                ('cvv', models.CharField(max_length=3)),
                ('ZipCode', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.user')),
            ],
        ),
    ]
