# Generated by Django 4.2.5 on 2023-10-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('tableSize', models.IntegerField(choices=[(2, 'Table for 2'), (4, 'Table for 4'), (8, 'Table for 8'), (12, 'Table for 12'), (20, 'Table for 20')])),
            ],
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table'),
        ),
    ]
